package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.stage.FileChooser;
import javafx.scene.control.Alert.AlertType;
import models.Client;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.imageio.ImageIO;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.embed.swing.SwingFXUtils;
import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;


public class AjouterSBController implements Initializable{
	@FXML
	private TextField txtid;
    @FXML
    private ComboBox txtfr;
	@FXML
	private TextField txtnom;
	@FXML
	private TextField txtprix_initial;
	@FXML
	private TextField txtprix_deal;
	@FXML
	private TextField txtdate_debut;
	@FXML
	private TextField txtdate_fin;
	@FXML
	private TextArea txtdescription;
	@FXML
	private Button btnajouterSB;
    @FXML
    private ImageView imageid;
	private String fr;
	 String imagename;
	
	public Connection getConnection() {
		Connection  conn;
		try {
			conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_deals","root","");
			return conn;
		} catch(Exception ex) {
			System.out.print("Error: "+ex.getMessage());
			return null; 
		}
	}
	   @FXML
	    void choose_file(ActionEvent event) {
		   FileChooser fileChooser = new FileChooser();
	        FileChooser.ExtensionFilter extFilterJPG = new FileChooser.ExtensionFilter("JPG files (*.jpg)", "*.JPG");
	        FileChooser.ExtensionFilter extFilterPNG = new FileChooser.ExtensionFilter("PNG files (*.png)", "*.PNG");
	        fileChooser.getExtensionFilters().addAll(extFilterJPG, extFilterPNG);
	        File file = fileChooser.showOpenDialog(null);
	        imagename = file.getAbsolutePath();

	        try {
	            BufferedImage bufferedImage = ImageIO.read(file);
	            Image image = SwingFXUtils.toFXImage(bufferedImage, null);
	            imageid.setImage(image);
	        } catch (IOException ignored) {
 
	        }
	    }
	// Event Listener on Button[#btnajouterSB].onAction
	@FXML
	public void ajouterSpa_Beauty(ActionEvent event) {
		// TODO Autogenerated
		PreparedStatement pst; 
    	
        String requete="INSERT INTO spabeauty(id,fournisseur,nom,prix_initial,prix_deal,date_deb,date_fin,description,image) VALUES ('" +txtid.getText()+"','"+txtfr.getSelectionModel().getSelectedItem().toString()+"','"+txtnom.getText()+"','"+txtprix_initial.getText()+"','"+txtprix_deal.getText()+"','"+txtdate_debut.getText()+"','"+txtdate_fin.getText()+"','"+txtdescription.getText()+"','"+imagename+"');";  
        if (!txtid.getText().equals("") && !txtfr.getSelectionModel().getSelectedItem().toString().equals("") && !txtnom.getText().equals("") && !txtprix_initial.getText().equals("") && !txtprix_deal.getText().equals("") && !txtdate_debut.getText().equals("") && !txtdate_fin.getText().equals("") && !txtdescription.getText().equals("")) 
        {
    	   Connection conn = getConnection();
    	   try {
           ResultSet rs = conn.createStatement().executeQuery("SELECT id FROM spabeauty where id='"+txtid.getText()+"'");
           if (rs.next()) {
        	   Alert alert = new Alert(AlertType.ERROR,"Deal avec ID : "+txtid.getText()+" existe déjà !",javafx.scene.control.ButtonType.OK);
      		   alert.showAndWait();
      		   txtid.clear();  
      		
    	   }
           else {
    	   
        try
        {
        	pst = conn.prepareStatement(requete);
            pst.executeUpdate(requete);
            System.out.println("Deal ajouté avec succès !");
            txtid.clear();  
            txtnom.clear();
   		   //txtfr.clear();
            txtprix_initial.clear();
            txtprix_deal.clear();
            txtdate_debut.clear();
   		   	txtdate_fin.clear();
   		   	txtdescription.clear();
            
        } catch (SQLException ex) {
            System.out.println("Erreur d'ajout !");
            Logger.getLogger(AjouterSBController.class.getName()).log(Level.SEVERE, null, ex);

        }

        Alert alert = new Alert(AlertType.CONFIRMATION,"Deal Beauty & Spa ajouté avec succès",javafx.scene.control.ButtonType.OK);
  		alert.showAndWait();}
    	   }catch (SQLException ex) {
               Logger.getLogger(AjouterSBController.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       else {
    	   Alert alert = new Alert(AlertType.WARNING,"Veuillez remplir tous les champs !",javafx.scene.control.ButtonType.OK);
  		 alert.showAndWait(); 
       }  
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub 
	    ObservableList <String> liste_fr = FXCollections.observableArrayList (); 
	    try {
        	Connection conn = getConnection();
            ResultSet rs = conn.createStatement().executeQuery("SELECT nom_commercial FROM fournisseurs");
            while(rs.next())
            { 
            	liste_fr.add(rs.getString("nom_commercial"));
            } 
           
        } catch (SQLException ex) {
            Logger.getLogger(AjouterSBController.class.getName()).log(Level.SEVERE, null, ex);
        }
	    txtfr.setItems( liste_fr);
	    txtfr.setVisibleRowCount(3);
		
	}
}
