package application;

import javafx.fxml.FXML;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

import javafx.scene.layout.BorderPane;
import javafx.scene.layout.Pane;

public class DealCltController {
	@FXML
	private BorderPane dealpane;
	@FXML
	private ImageView spaimg;
	@FXML
	private ImageView restauimg;
	@FXML
	private ImageView hotelimg;

	// Event Listener on ImageView[#spaimg].onMouseClicked
	@FXML
	public void showSpa_Beauty(MouseEvent event) {
		// TODO Autogenerated
		FxmlLoader object = new FxmlLoader();
		Pane view = object.getPage("SpaBeauty");
		dealpane.setCenter(view);
	}
	// Event Listener on ImageView[#restauimg].onMouseClicked
	@FXML
	public void showRestauration(MouseEvent event) {
		// TODO Autogenerated
		FxmlLoader object = new FxmlLoader();
		Pane view = object.getPage("Restauclt");
		dealpane.setCenter(view);
	}
	// Event Listener on ImageView[#hotelimg].onMouseClicked
	@FXML
	public void showHotellerie(MouseEvent event) {
		// TODO Autogenerated
	}
}
