package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import models.Vente;

public class HomeAdminController implements Initializable{
	@FXML
	private BorderPane mainpane;
    @FXML
    private Label nbclt;

    @FXML
    private Label nbdeals;

    @FXML
    private Label nbfr;

    @FXML
    private Label nbventes;
	@FXML
	private TextField txtdate;
	@FXML
	private TableView <Vente> tabventes;
	@FXML
	private TableColumn<Vente,Integer> colnum;
	@FXML
	private TableColumn<Vente,String> coldate;
	@FXML
	private TableColumn<Vente,String> coldeal;
	@FXML
	private TableColumn <Vente,Float>colprix;
	@FXML
	private TableColumn <Vente,String>colfr;
	@FXML
	private TableColumn<Vente,Integer> colcin;
	
	// Event Listener on Button.onAction
	@FXML
	public void clients(ActionEvent event) {
		// TODO Autogenerated
		FxmlLoader object = new FxmlLoader();
		Pane view = object.getPage("Client");
		mainpane.setCenter(view); 
	}

	// Event Listener on Button.onAction
	@FXML
	public void fournisseurs(ActionEvent event) {
		// TODO Autogenerated
		FxmlLoader object = new FxmlLoader();
		Pane view = object.getPage("Fournisseur");
		mainpane.setCenter(view);
	}

	// Event Listener on Button.onAction
	@FXML
	public void deals(ActionEvent event) {
		// TODO Autogenerated
		FxmlLoader object = new FxmlLoader();
		Pane view = object.getPage("Deal");
		mainpane.setCenter(view);
	}

	// Event Listener on Button.onAction
	@FXML
	public void ventes(ActionEvent event) {
		// TODO Autogenerated
		FxmlLoader object = new FxmlLoader();
		Pane view = object.getPage("Ventes");
		mainpane.setCenter(view);
	}

	// Event Listener on Button.onAction
	@FXML
	public void quitter(ActionEvent event) throws IOException {
		// TODO Autogenerated
	 Stage stage = new Stage();
   	 mainpane.getScene().getWindow().hide();
     Parent root;
     root = FXMLLoader.load(getClass().getResource("Home.fxml"));
     Scene scene = new Scene(root,600,400);
     stage.setScene(scene);
     stage.show();
     stage.setResizable(false);
	}
	public Connection getConnection() {
		Connection  conn;
		try {
			conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_deals","root","");
			return conn;
		} catch(Exception ex) {
			System.out.print("Error: "+ex.getMessage());
			return null; 
		}
	}
	public void ventes_auj() {
		// TODO Autogenerated
		ObservableList<Vente> data = FXCollections.observableArrayList();

		Connection conn = getConnection();
		Date date = new Date( System.currentTimeMillis() );
	    SimpleDateFormat sdf = new SimpleDateFormat( "dd/MM/yyyy" );
 
	    	try {
	           ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM vente where date like '"+sdf.format( date )+"'");
	           while (rs.next()) {
	        	   data.add(new Vente(rs.getInt("num"),rs.getInt("cin_clt"),rs.getString("fournisseur"),rs.getString("date"),rs.getString("deal"),rs.getFloat("prixdeal")));

	           }

		} catch (SQLException ex) {
            System.out.println("Erreur d'ajout !");
            Logger.getLogger(VentesController.class.getName()).log(Level.SEVERE, null, ex);

        }
	
				colnum.setCellValueFactory(new PropertyValueFactory<>("num"));
	    		coldeal.setCellValueFactory(new PropertyValueFactory<>("deal"));
				colfr.setCellValueFactory(new PropertyValueFactory<>("fournisseur"));
				colprix.setCellValueFactory(new PropertyValueFactory<>("prixdeal"));
				coldate.setCellValueFactory(new PropertyValueFactory<>("date"));
				colcin.setCellValueFactory(new PropertyValueFactory<>("cin_clt"));

				tabventes.setItems(data);

	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		Connection conn = getConnection();
		
		int c=0,f=0,sp=0,v=0,r=0;
		 
    	try {
           ResultSet rsv = conn.createStatement().executeQuery("SELECT * FROM vente");
           while (rsv.next()) {
        	   v=v+1;
           }
           ResultSet rsc = conn.createStatement().executeQuery("SELECT * FROM clients");
           while (rsc.next()) {
        	   c=c+1;
           }
           ResultSet rsf = conn.createStatement().executeQuery("SELECT * FROM fournisseurs");
           while (rsf.next()) {
        	   f=f+1;
           }
           ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM spabeauty");
           while (rs.next()) {
        	   sp=sp+1;
           }
           ResultSet rsr = conn.createStatement().executeQuery("SELECT * FROM restauration");
           while (rsr.next()) {
        	   r=r+1;
           }

	} catch (SQLException ex) {
        Logger.getLogger(VentesController.class.getName()).log(Level.SEVERE, null, ex);

	}
    	nbclt.setText(Integer.toString(c));
    	nbfr.setText(Integer.toString(f));
    	nbdeals.setText(Integer.toString(sp+r));
    	nbventes.setText(Integer.toString(v));
    	
    	ventes_auj();
	}

}
