package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.scene.control.Alert.AlertType;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

public class LoginController implements Initializable {
 
	@FXML
	private TextField txtusername;
	@FXML
	private TextField txtpassword;
	@FXML
	private Button btnconnexion;
	@FXML 
	private VBox VBox;
    @FXML
    private Button btnhome;
    @FXML
    private Button btnconnclient;
    
    
	public Connection getConnection() {
		Connection  conn;
		try {
			conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_deals","root","");
			return conn;
		} catch(Exception ex) {
			System.out.print("Error: "+ex.getMessage());
			return null; 
		}
	}
	// Event Listener on Button[#btnconnexion].onAction 
	@FXML 
	public void seconnecter(ActionEvent event) throws IOException { 
		// TODO Autogenerated
		
		if(!txtusername.getText().equals("")&& !txtpassword.getText().equals("")) 
		{
			if(txtusername.getText().equals("user")&& txtpassword.getText().equals("user"))
			{
				System.out.println("Bienvenu Admin");
				VBox.getScene().getWindow().hide();
				Stage stage = new Stage();
				Parent rootA;
				rootA = FXMLLoader.load(getClass().getResource("HomeAdmin.fxml"));
				Scene scene = new Scene(rootA,1040,710); 
				stage.setScene(scene);
				stage.show();
				stage.setResizable(false);
			}
			else {
				Alert alert = new Alert(AlertType.ERROR,"Veuillez vérifiez votre Identifiant et votre Mot de passe !!",javafx.scene.control.ButtonType.OK);
				alert.showAndWait();
				} 
		 }
		 else {
			 Alert alert = new Alert(AlertType.WARNING,"Veuillez remplir tous les champs !",javafx.scene.control.ButtonType.OK);
	  		 alert.showAndWait();
		 }
	}
    @FXML
    void backHome(ActionEvent event) throws IOException {
    	Stage stage = new Stage();
    	btnhome.getScene().getWindow().hide();
        Parent root;
        root = FXMLLoader.load(getClass().getResource("Home.fxml"));
        Scene scene = new Scene(root,600,400);
        stage.setScene(scene);
        stage.show();
        stage.setResizable(false);
    }
    
    
    @FXML
    void seconnecter_clt(ActionEvent event) throws IOException {
    	PreparedStatement pst;
    	Connection conn = getConnection();
    	if(!txtusername.getText().equals("")&& !txtpassword.getText().equals("")) 
    	{String q1 = "SELECT * FROM clients WHERE email=? AND mdp=?";
        try {
            pst = conn.prepareStatement(q1);
            pst.setString(1, txtusername.getText());
            pst.setString(2, txtpassword.getText());
            
            ResultSet rs = pst.executeQuery();
            int count = 0;
            while(rs.next())
            {
                count++;
            }
            
            if (count==1)
            {
                System.out.println("Bienvenu ");
                 
                Stage stage = new Stage();
                VBox.getScene().getWindow().hide();
                Parent rootA;
                rootA = FXMLLoader.load(getClass().getResource("HomeClient.fxml"));
                Scene scene = new Scene(rootA,1040,710);
                stage.setScene(scene);
                stage.show();
                stage.setResizable(false);
                ResultSet rsuser = conn.createStatement().executeQuery ("SELECT * FROM clients where email like '"+txtusername.getText()+"'");
                while(rsuser.next()) {

                	int cin=rsuser.getInt("CIN");
                	 String nom=rsuser.getString("nom");
                	 String prenom=rsuser.getString("prenom");
                	 String email=rsuser.getString("email");
                	 String mdp=rsuser.getString("mdp");
                	 int tel=rsuser.getInt("tel");
                	 String adresse=rsuser.getString("adresse");
                	 
                     String requete="INSERT INTO currentuser VALUES ('" +cin+"','"+nom+"','"+prenom+"','"+email+"','"+mdp+"','"+tel+"','"+adresse+"');";   
                     try
                     {	
                    	 pst = conn.prepareStatement(requete);
                         pst.executeUpdate(requete);
                         System.out.println("user ajouté avec succès !");
                     }catch (SQLException ex) {
                         System.out.println("Erreur d'ajout !");
                	 
                }
            }
                }
            else
            {
                Alert alert = new Alert(Alert.AlertType.ERROR);
                alert.setHeaderText(null);
                alert.setContentText("Veuillez vérifiez votre Identifiant et votre Mot de passe !");
                alert.showAndWait();
            }
            
        } catch (SQLException ex) {
        }
    	}
    	else {
    		 Alert alert = new Alert(AlertType.WARNING,"Veuillez remplir tous les champs !",javafx.scene.control.ButtonType.OK);
	  		 alert.showAndWait();
    	}
    	
    }
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
    	/*Connection conn = getConnection();
    	PreparedStatement pst;

		if(!txtusername.getText().equals("")&& !txtpassword.getText().equals("")) {
			  try {
		     ResultSet rsuser = conn.createStatement().executeQuery ("SELECT * FROM clients where email like '"+txtusername.getText()+"'");
           
		     while(rsuser.next()) {

             	int cin=rsuser.getInt("CIN");
             	 String nom=rsuser.getString("nom");
             	 String prenom=rsuser.getString("prenom");
             	 String email=rsuser.getString("email");
             	 String mdp=rsuser.getString("mdp");
             	 int tel=rsuser.getInt("tel");
             	 String adresse=rsuser.getString("adresse");
             	 
                  String requete="INSERT INTO currentuser VALUES ('" +cin+"','"+nom+"','"+prenom+"','"+email+"','"+mdp+"','"+tel+"','"+adresse+"');";   
                  try
                  {	
                 	 pst = conn.prepareStatement(requete);
                      pst.executeUpdate(requete);
                      System.out.println("user ajouté avec succès !");
                  }catch (SQLException ex) {
                      System.out.println("Erreur d'ajout !"); }
             }
             
		}catch (SQLException ex) {
            System.out.println("Erreur d'ajout !");}
		
	}*/

}}
 